version: "3"
services:
    frontend:
      container_name: "commuen_front"
      build:
        context: .
        dockerfile: Dockerfile
      # コードの変更を仮想環境でもリアルタイムで変更したい
      volumes:
        - .:/app
      ports:
        - 8080:8080